//! Markdown Documentation Generator
//! 
//! Generates Markdown documentation files for static site generators and GitHub.

use super::{DocGeneratorConfig, ExtractedDocumentation, DocumentationItem, ItemKind};
use crate::error::Error;
use std::path::Path;
use std::fs;

/// Markdown documentation generator
pub struct MarkdownGenerator<'a> {
    config: &'a DocGeneratorConfig,
}

impl<'a> MarkdownGenerator<'a> {
    /// Create a new Markdown generator
    pub fn new(config: &'a DocGeneratorConfig) -> Self {
        Self { config }
    }

    /// Generate the main README file
    pub fn generate_readme(
        &self,
        docs: &[ExtractedDocumentation],
        output_dir: &Path,
    ) -> Result<(), Error> {
        let mut content = String::new();
        
        // Title and description
        content.push_str(&format!("# {}\n\n", self.config.title));
        
        if let Some(description) = &self.config.description {
            content.push_str(&format!("{}\n\n", description));
        }
        
        // Project metadata
        if let Some(version) = &self.config.version {
            content.push_str(&format!("**Version:** {}\n\n", version));
        }
        
        if !self.config.authors.is_empty() {
            content.push_str("**Authors:**\n");
            for author in &self.config.authors {
                content.push_str(&format!("- {}\n", author));
            }
            content.push('\n');
        }

        // Table of contents
        content.push_str("## Table of Contents\n\n");
        for doc in docs {
            content.push_str(&format!("- [{}]({})\n", doc.module_name, self.module_filename(&doc.module_name)));
        }
        content.push('\n');

        // Modules overview
        content.push_str("## Modules Overview\n\n");
        for doc in docs {
            content.push_str(&format!("### {}\n\n", doc.module_name));
            content.push_str(&format!("**File:** `{}`\n\n", doc.file_path.display()));
            
            // Count items by type
            let mut counts = std::collections::HashMap::new();
            for item in &doc.items {
                *counts.entry(&item.kind).or_insert(0) += 1;
            }
            
            content.push_str("**Contains:**\n");
            for (kind, count) in counts {
                content.push_str(&format!("- {} {}{}\n", count, kind.to_string(), if count == 1 { "" } else { "s" }));
            }
            content.push('\n');
        }

        // Statistics
        let total_items: usize = docs.iter().map(|d| d.items.len()).sum();
        content.push_str("## Documentation Statistics\n\n");
        content.push_str(&format!("- **Total modules:** {}\n", docs.len()));
        content.push_str(&format!("- **Total documented items:** {}\n", total_items));
        content.push('\n');

        // Footer
        content.push_str("---\n\n");
        content.push_str("*Generated by CURSED Documentation Generator*\n");

        let output_file = output_dir.join("README.md");
        fs::write(&output_file, content).map_err(Error::Io)?;

        Ok(())
    }

    /// Generate documentation for a single module
    pub fn generate_module_doc(
        &self,
        doc: &ExtractedDocumentation,
        output_dir: &Path,
    ) -> Result<(), Error> {
        let mut content = String::new();
        
        // Module header
        content.push_str(&format!("# Module: {}\n\n", doc.module_name));
        content.push_str(&format!("**File:** `{}`\n\n", doc.file_path.display()));
        
        if let Some(package) = &doc.package_name {
            content.push_str(&format!("**Package:** {}\n\n", package));
        }

        // Navigation
        content.push_str("[← Back to Documentation Index](README.md)\n\n");

        // Imports section
        if !doc.imports.is_empty() {
            content.push_str("## Imports\n\n");
            for import in &doc.imports {
                content.push_str(&format!("- `{}`\n", import));
            }
            content.push('\n');
        }

        // Group items by kind
        let mut grouped_items = std::collections::HashMap::new();
        for item in &doc.items {
            grouped_items.entry(&item.kind).or_insert_with(Vec::new).push(item);
        }

        // Generate table of contents
        content.push_str("## Table of Contents\n\n");
        for (kind, items) in &grouped_items {
            content.push_str(&format!("### {}\n\n", self.plural_kind_name(kind)));
            for item in items {
                content.push_str(&format!("- [`{}`](#{}) - {}\n", 
                    item.name, 
                    self.anchor_name(&item.name),
                    item.summary));
            }
            content.push('\n');
        }

        // Generate detailed documentation for each kind
        for (kind, items) in grouped_items {
            content.push_str(&format!("## {}\n\n", self.plural_kind_name(&kind)));
            
            for item in items {
                self.generate_item_documentation(item, &mut content);
            }
        }

        // Footer
        content.push_str("---\n\n");
        content.push_str(&format!("*Module documentation generated from `{}`*\n", doc.file_path.display()));

        let output_file = output_dir.join(self.module_filename(&doc.module_name));
        fs::write(&output_file, content).map_err(Error::Io)?;

        Ok(())
    }

    /// Generate documentation for a single item
    fn generate_item_documentation(&self, item: &DocumentationItem, content: &mut String) {
        // Item header
        content.push_str(&format!("### {}\n\n", item.name));
        
        // Signature
        if let Some(signature) = &item.signature {
            content.push_str("```cursed\n");
            content.push_str(signature);
            content.push_str("\n```\n\n");
        }

        // Summary and description
        content.push_str(&format!("**Summary:** {}\n\n", item.summary));
        
        if !item.description.is_empty() && item.description != item.summary {
            content.push_str(&format!("{}\n\n", item.description));
        }

        // Parameters
        if !item.parameters.is_empty() {
            content.push_str("**Parameters:**\n\n");
            for param in &item.parameters {
                content.push_str(&format!("- **`{}`**", param.name));
                
                if let Some(type_name) = &param.type_name {
                    content.push_str(&format!(" (`{}`)", type_name));
                }
                
                if let Some(default) = &param.default_value {
                    content.push_str(&format!(" = `{}`", default));
                }
                
                content.push_str(&format!(" - {}\n", param.description));
            }
            content.push('\n');
        }

        // Return type
        if let Some(return_type) = &item.return_type {
            content.push_str(&format!("**Returns:** `{}`\n\n", return_type));
        }

        // Examples
        if !item.examples.is_empty() {
            content.push_str("**Examples:**\n\n");
            for (i, example) in item.examples.iter().enumerate() {
                if let Some(title) = &example.title {
                    content.push_str(&format!("#### {}\n\n", title));
                } else if item.examples.len() > 1 {
                    content.push_str(&format!("#### Example {}\n\n", i + 1));
                }
                
                if let Some(description) = &example.description {
                    content.push_str(&format!("{}\n\n", description));
                }
                
                content.push_str(&format!("```{}\n", example.language));
                content.push_str(&example.code);
                content.push_str("\n```\n\n");
                
                if let Some(output) = &example.output {
                    content.push_str("**Output:**\n");
                    content.push_str("```\n");
                    content.push_str(output);
                    content.push_str("\n```\n\n");
                }
            }
        }

        // Source code
        if let Some(source_code) = &item.source_code {
            if self.config.include_examples {
                content.push_str("<details>\n<summary>View Source Code</summary>\n\n");
                content.push_str("```cursed\n");
                content.push_str(source_code);
                content.push_str("\n```\n\n");
                content.push_str("</details>\n\n");
            }
        }

        // Module and location info
        content.push_str(&format!("**Module:** `{}`  \n", item.module));
        content.push_str(&format!("**Visibility:** {}  \n\n", 
            match item.visibility {
                super::Visibility::Public => "Public",
                super::Visibility::Private => "Private",
            }));

        content.push_str("---\n\n");
    }

    /// Generate filename for a module
    fn module_filename(&self, module_name: &str) -> String {
        format!("{}.md", module_name.replace("::", "_"))
    }

    /// Generate anchor name for linking
    fn anchor_name(&self, name: &str) -> String {
        name.to_lowercase().replace(' ', "-").replace(&['(', ')', '[', ']', '{', '}'][..], "")
    }

    /// Get plural form of item kind name
    fn plural_kind_name(&self, kind: &ItemKind) -> String {
        match kind {
            ItemKind::Function => "Functions".to_string(),
            ItemKind::Struct => "Structs".to_string(),
            ItemKind::Interface => "Interfaces".to_string(),
            ItemKind::Variable => "Variables".to_string(),
            ItemKind::Constant => "Constants".to_string(),
            ItemKind::Type => "Types".to_string(),
            ItemKind::Module => "Modules".to_string(),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::error::SourceLocation;
    use std::collections::HashMap;

    fn create_test_config() -> DocGeneratorConfig {
        DocGeneratorConfig {
            output_dir: std::path::PathBuf::from("test_docs"),
            format: super::super::DocFormat::Markdown,
            include_examples: true,
            include_private: false,
            generate_cross_refs: true,
            custom_css: None,
            template_dir: None,
            title: "Test Documentation".to_string(),
            description: Some("Test project documentation".to_string()),
            version: Some("1.0.0".to_string()),
            authors: vec!["Test Author".to_string()],
            base_url: None,
        }
    }

    fn create_test_item() -> DocumentationItem {
        DocumentationItem {
            name: "test_function".to_string(),
            kind: ItemKind::Function,
            visibility: super::super::Visibility::Public,
            module: "test_module".to_string(),
            summary: "A test function".to_string(),
            description: "This is a test function for unit testing".to_string(),
            signature: Some("slay test_function(param: string) -> i32".to_string()),
            parameters: vec![super::super::Parameter {
                name: "param".to_string(),
                type_name: Some("string".to_string()),
                description: "A test parameter".to_string(),
                default_value: None,
            }],
            return_type: Some("i32".to_string()),
            examples: vec![super::super::Example {
                title: Some("Basic Usage".to_string()),
                description: Some("Shows how to use the function".to_string()),
                code: "let result = test_function(\"hello\");".to_string(),
                language: "cursed".to_string(),
                output: Some("42".to_string()),
            }],
            tags: HashMap::new(),
            location: SourceLocation { line: 1, column: 1, file: None },
            source_code: Some("slay test_function(param: string) -> i32 {\n    return 42;\n}".to_string()),
        }
    }

    #[test]
    fn test_module_filename() {
        let config = create_test_config();
        let generator = MarkdownGenerator::new(&config);
        
        assert_eq!(generator.module_filename("simple"), "simple.md");
        assert_eq!(generator.module_filename("nested::module"), "nested_module.md");
    }

    #[test]
    fn test_anchor_name() {
        let config = create_test_config();
        let generator = MarkdownGenerator::new(&config);
        
        assert_eq!(generator.anchor_name("simple_function"), "simple_function");
        assert_eq!(generator.anchor_name("Complex Function()"), "complex-function");
        assert_eq!(generator.anchor_name("Array[Type]"), "arraytype");
    }

    #[test]
    fn test_plural_kind_name() {
        let config = create_test_config();
        let generator = MarkdownGenerator::new(&config);
        
        assert_eq!(generator.plural_kind_name(&ItemKind::Function), "Functions");
        assert_eq!(generator.plural_kind_name(&ItemKind::Struct), "Structs");
        assert_eq!(generator.plural_kind_name(&ItemKind::Interface), "Interfaces");
    }

    #[test]
    fn test_generate_item_documentation() {
        let config = create_test_config();
        let generator = MarkdownGenerator::new(&config);
        let item = create_test_item();
        
        let mut content = String::new();
        generator.generate_item_documentation(&item, &mut content);
        
        assert!(content.contains("### test_function"));
        assert!(content.contains("```cursed"));
        assert!(content.contains("slay test_function(param: string) -> i32"));
        assert!(content.contains("**Parameters:**"));
        assert!(content.contains("- **`param`** (`string`)"));
        assert!(content.contains("**Returns:** `i32`"));
        assert!(content.contains("**Examples:**"));
        assert!(content.contains("#### Basic Usage"));
        assert!(content.contains("<details>"));
        assert!(content.contains("**Module:** `test_module`"));
    }
}
