#!/usr/bin/env python3
"""
Comprehensive stdlib module testing audit and verification system.
Identifies missing tests, creates standardized test patterns, and implements automated testing.
"""

import os
import glob
import json
import sys
from pathlib import Path
from typing import Dict, List, Set, Tuple
import re

class StdlibTestAuditor:
    def __init__(self, stdlib_dir: str = "stdlib"):
        self.stdlib_dir = Path(stdlib_dir)
        self.modules = {}
        self.test_patterns = {}
        self.missing_tests = []
        self.coverage_report = {}
        
    def discover_modules(self) -> Dict[str, Dict]:
        """Discover all stdlib modules and their current test status."""
        modules = {}
        
        for module_dir in self.stdlib_dir.iterdir():
            if module_dir.is_dir() and not module_dir.name.startswith('.'):
                module_name = module_dir.name
                modules[module_name] = {
                    'path': module_dir,
                    'has_mod_file': (module_dir / 'mod.csd').exists(),
                    'has_test_file': False,
                    'test_files': [],
                    'functions': [],
                    'dependencies': [],
                    'coverage': 0
                }
                
                # Find test files
                test_files = list(module_dir.glob('test_*.csd')) + list(module_dir.glob('*_test.csd'))
                modules[module_name]['test_files'] = test_files
                modules[module_name]['has_test_file'] = len(test_files) > 0
                
                # Analyze module file for functions
                if modules[module_name]['has_mod_file']:
                    mod_file = module_dir / 'mod.csd'
                    try:
                        with open(mod_file, 'r') as f:
                            content = f.read()
                            # Extract function definitions
                            functions = re.findall(r'slay\s+([a-zA-Z_][a-zA-Z0-9_]*)\s*\(', content)
                            modules[module_name]['functions'] = functions
                            
                            # Extract dependencies
                            deps = re.findall(r'yeet\s+"([^"]+)"', content)
                            modules[module_name]['dependencies'] = deps
                    except Exception as e:
                        print(f"Error reading {mod_file}: {e}")
                        
        return modules
    
    def audit_missing_tests(self) -> List[str]:
        """Identify modules without proper test coverage."""
        missing = []
        
        for module_name, info in self.modules.items():
            if not info['has_test_file']:
                missing.append(module_name)
            elif len(info['functions']) > 0:
                # Check if all functions have tests
                test_coverage = 0
                for test_file in info['test_files']:
                    try:
                        with open(test_file, 'r') as f:
                            test_content = f.read()
                            for func in info['functions']:
                                if func in test_content:
                                    test_coverage += 1
                    except Exception as e:
                        print(f"Error reading {test_file}: {e}")
                
                coverage_pct = (test_coverage / len(info['functions'])) * 100 if info['functions'] else 100
                info['coverage'] = coverage_pct
                
                if coverage_pct < 80:  # Less than 80% coverage
                    missing.append(f"{module_name} (coverage: {coverage_pct:.1f}%)")
                    
        return missing
    
    def generate_test_template(self, module_name: str, functions: List[str]) -> str:
        """Generate standardized test template for a module."""
        template = f'''yeet "testz"
yeet "{module_name}"

# Comprehensive test suite for {module_name} module
# Generated by stdlib test auditor

'''
        
        for func in functions:
            template += f'''test_start("test_{func}")
# Test {func} function
# TODO: Implement test cases for {func}
sus result lit = {func}("test_input")
assert_true(result)
print_test_summary()

'''
        
        template += '''# Integration tests
test_start("integration_tests")
# Test module integration with other stdlib modules
# TODO: Add integration test cases
print_test_summary()

# Performance benchmarks
test_start("performance_benchmarks")
# TODO: Add performance benchmarks
print_test_summary()

# Edge case testing
test_start("edge_cases")
# TODO: Add edge case testing
print_test_summary()
'''
        
        return template
    
    def create_missing_test_files(self):
        """Create test files for modules that don't have them."""
        for module_name, info in self.modules.items():
            if not info['has_test_file'] and info['functions']:
                test_file = info['path'] / f"test_{module_name}.csd"
                template = self.generate_test_template(module_name, info['functions'])
                
                try:
                    with open(test_file, 'w') as f:
                        f.write(template)
                    print(f"Created test file: {test_file}")
                except Exception as e:
                    print(f"Error creating test file {test_file}: {e}")
    
    def generate_test_runner(self) -> str:
        """Generate comprehensive test runner script."""
        runner = '''#!/usr/bin/env python3
"""
Comprehensive stdlib test runner for CURSED language.
Executes all stdlib module tests with performance monitoring and coverage reporting.
"""

import os
import subprocess
import time
import json
from pathlib import Path
from typing import Dict, List, Tuple

class StdlibTestRunner:
    def __init__(self):
        self.test_results = {}
        self.performance_metrics = {}
        self.coverage_data = {}
        
    def run_module_test(self, module_name: str, test_file: Path) -> Tuple[bool, float, str]:
        """Run a single module test and return results."""
        start_time = time.time()
        
        try:
            # Test interpretation mode
            interp_result = subprocess.run(
                ['cargo', 'run', '--bin', 'cursed', str(test_file)],
                capture_output=True,
                text=True,
                timeout=30
            )
            
            # Test compilation mode
            comp_result = subprocess.run(
                ['cargo', 'run', '--bin', 'cursed', '--', 'compile', str(test_file)],
                capture_output=True,
                text=True,
                timeout=30
            )
            
            executable = test_file.parent / test_file.stem
            if executable.exists():
                exec_result = subprocess.run(
                    [str(executable)],
                    capture_output=True,
                    text=True,
                    timeout=30
                )
                os.remove(executable)
            else:
                exec_result = None
                
            execution_time = time.time() - start_time
            
            # Check results
            success = (interp_result.returncode == 0 and 
                      comp_result.returncode == 0 and
                      (exec_result is None or exec_result.returncode == 0))
            
            output = f"Interp: {interp_result.stdout}\\nComp: {comp_result.stdout}"
            if exec_result:
                output += f"\\nExec: {exec_result.stdout}"
                
            return success, execution_time, output
            
        except subprocess.TimeoutExpired:
            return False, time.time() - start_time, "Test timed out"
        except Exception as e:
            return False, time.time() - start_time, f"Error: {str(e)}"
    
    def run_all_tests(self) -> Dict:
        """Run all stdlib module tests."""
        stdlib_dir = Path("stdlib")
        total_tests = 0
        passed_tests = 0
        
        print("Running comprehensive stdlib test suite...")
        print("=" * 60)
        
        for module_dir in stdlib_dir.iterdir():
            if module_dir.is_dir() and not module_dir.name.startswith('.'):
                module_name = module_dir.name
                test_files = list(module_dir.glob('test_*.csd')) + list(module_dir.glob('*_test.csd'))
                
                if not test_files:
                    print(f"❌ {module_name}: No test files found")
                    continue
                    
                module_results = []
                for test_file in test_files:
                    total_tests += 1
                    success, exec_time, output = self.run_module_test(module_name, test_file)
                    
                    if success:
                        passed_tests += 1
                        print(f"✅ {module_name}/{test_file.name}: PASSED ({exec_time:.2f}s)")
                    else:
                        print(f"❌ {module_name}/{test_file.name}: FAILED ({exec_time:.2f}s)")
                        if output:
                            print(f"   Output: {output[:100]}...")
                    
                    module_results.append({
                        'test_file': test_file.name,
                        'success': success,
                        'execution_time': exec_time,
                        'output': output
                    })
                
                self.test_results[module_name] = module_results
        
        print("=" * 60)
        print(f"Test Summary: {passed_tests}/{total_tests} tests passed ({(passed_tests/total_tests)*100:.1f}%)")
        
        return {
            'total_tests': total_tests,
            'passed_tests': passed_tests,
            'pass_rate': (passed_tests/total_tests)*100 if total_tests > 0 else 0,
            'results': self.test_results
        }
    
    def generate_coverage_report(self) -> str:
        """Generate detailed coverage report."""
        report = "# Stdlib Test Coverage Report\\n\\n"
        
        for module_name, results in self.test_results.items():
            total_tests = len(results)
            passed_tests = sum(1 for r in results if r['success'])
            pass_rate = (passed_tests / total_tests) * 100 if total_tests > 0 else 0
            
            status = "✅" if pass_rate >= 80 else "⚠️" if pass_rate >= 50 else "❌"
            report += f"{status} **{module_name}**: {passed_tests}/{total_tests} ({pass_rate:.1f}%)\\n"
        
        return report
    
    def run_performance_benchmarks(self):
        """Run performance benchmarks for critical modules."""
        critical_modules = ['math', 'string', 'crypto', 'collections', 'io', 'json']
        
        print("Running performance benchmarks...")
        for module in critical_modules:
            module_dir = Path(f"stdlib/{module}")
            if module_dir.exists():
                # Run benchmark tests
                benchmark_files = list(module_dir.glob('benchmark_*.csd'))
                for benchmark_file in benchmark_files:
                    print(f"📊 Benchmarking {module}/{benchmark_file.name}")
                    # TODO: Implement benchmark execution

if __name__ == "__main__":
    runner = StdlibTestRunner()
    results = runner.run_all_tests()
    
    # Generate reports
    with open("stdlib_test_results.json", "w") as f:
        json.dump(results, f, indent=2)
    
    coverage_report = runner.generate_coverage_report()
    with open("stdlib_coverage_report.md", "w") as f:
        f.write(coverage_report)
    
    print("\\nReports generated:")
    print("- stdlib_test_results.json")
    print("- stdlib_coverage_report.md")
'''
        
        return runner
    
    def run_audit(self):
        """Run complete audit and generate reports."""
        print("Starting comprehensive stdlib test audit...")
        
        # Discover modules
        self.modules = self.discover_modules()
        print(f"Discovered {len(self.modules)} stdlib modules")
        
        # Audit missing tests
        self.missing_tests = self.audit_missing_tests()
        print(f"Found {len(self.missing_tests)} modules with missing or insufficient tests")
        
        # Generate reports
        self.generate_audit_report()
        self.create_missing_test_files()
        
        # Create test runner
        runner_script = self.generate_test_runner()
        with open("stdlib_test_runner.py", "w") as f:
            f.write(runner_script)
        
        print("Audit complete!")
        print("Generated:")
        print("- stdlib_audit_report.json")
        print("- stdlib_test_runner.py")
        print("- Missing test files created")
    
    def generate_audit_report(self):
        """Generate comprehensive audit report."""
        report = {
            'total_modules': len(self.modules),
            'modules_with_tests': len([m for m in self.modules.values() if m['has_test_file']]),
            'modules_without_tests': len([m for m in self.modules.values() if not m['has_test_file']]),
            'missing_tests': self.missing_tests,
            'modules': self.modules,
            'recommendations': [
                "Create test files for modules without tests",
                "Improve test coverage for modules below 80%",
                "Add integration tests between modules",
                "Implement performance benchmarks for critical modules",
                "Add edge case testing for all modules"
            ]
        }
        
        with open("stdlib_audit_report.json", "w") as f:
            json.dump(report, f, indent=2, default=str)

if __name__ == "__main__":
    auditor = StdlibTestAuditor()
    auditor.run_audit()
