; Generated by CURSED compiler
; LLVM IR output for debugging and inspection
;
; ModuleID = 'test_simple'
source_filename = "test_simple"

@str_literal_0 = private constant [17 x i8] c"Hello, IR output!"
@str_literal_1 = private constant [1 x i8] c"}"

declare i32 @puts(ptr)

define i32 @vibez_spill_direct(ptr %0) {
entry:
  %puts_call = call i32 @puts(ptr %0)
  ret i32 0
}

define i32 @main() {
entry:
  ret i32 0
}

define i32 @_test_main() {
entry:
  ret i32 0
}

define i32 @_main_main() {
entry:
  ret i32 0
}
