/// Integration tests for LLVM package system
/// 
/// Tests the integration between the package manager and LLVM compilation pipeline.

use cursed::codegen::llvm::{LlvmCodeGenerator, LlvmPackageConfig, LlvmPackageIntegration};
use cursed::package_manager::{PackageManager, PackageManagerConfig};
use std::sync::{Arc, Mutex};

#[tokio::test]
async fn test_llvm_package_integration_initialization() {
    // Create package manager
    let package_manager_config = PackageManagerConfig::default();
    let package_manager = Arc::new(Mutex::new(
        PackageManager::new(package_manager_config).unwrap()
    ));
    
    // Create LLVM code generator
    let mut codegen = LlvmCodeGenerator::new().unwrap();
    
    // Initialize package integration
    let package_config = LlvmPackageConfig::default();
    let result = codegen.initialize_package_integration(package_manager, package_config);
    
    assert!(result.is_ok());
    assert!(codegen.package_integration_enabled());
}

#[tokio::test]
async fn test_simple_compilation_with_packages() {
    // Create package manager
    let package_manager_config = PackageManagerConfig::default();
    let package_manager = Arc::new(Mutex::new(
        PackageManager::new(package_manager_config).unwrap()
    ));
    
    // Create LLVM code generator with package integration
    let mut codegen = LlvmCodeGenerator::new().unwrap();
    let package_config = LlvmPackageConfig {
        auto_install_packages: false, // Disable auto-install for test
        ..LlvmPackageConfig::default()
    };
    
    codegen.initialize_package_integration(package_manager, package_config).unwrap();
    
    // Simple CURSED source without external packages
    let source = r#"
slay main() {
    capicola("Hello, World!");
}
"#;
    
    let result = codegen.compile_with_packages(source, None).await;
    assert!(result.is_ok());
    
    let ir = result.unwrap();
    assert!(ir.contains("Generated by CURSED Compiler with Package Integration"));
    assert!(ir.contains("target datalayout"));
    assert!(ir.contains("target triple"));
}

#[tokio::test]
async fn test_stdlib_import_compilation() {
    // Create package manager
    let package_manager_config = PackageManagerConfig::default();
    let package_manager = Arc::new(Mutex::new(
        PackageManager::new(package_manager_config).unwrap()
    ));
    
    // Create LLVM code generator with package integration
    let mut codegen = LlvmCodeGenerator::new().unwrap();
    let package_config = LlvmPackageConfig::default();
    
    codegen.initialize_package_integration(package_manager, package_config).unwrap();
    
    // CURSED source with standard library import
    let source = r#"
import "stdlib::io"

slay main() {
    println("Hello with packages!");
}
"#;
    
    let result = codegen.compile_with_packages(source, None).await;
    assert!(result.is_ok());
    
    let ir = result.unwrap();
    assert!(ir.contains("Generated by CURSED Compiler with Package Integration"));
}

#[tokio::test]
async fn test_package_symbol_resolution() {
    // Create package manager
    let package_manager_config = PackageManagerConfig::default();
    let package_manager = Arc::new(Mutex::new(
        PackageManager::new(package_manager_config).unwrap()
    ));
    
    // Create LLVM code generator with package integration
    let mut codegen = LlvmCodeGenerator::new().unwrap();
    let package_config = LlvmPackageConfig::default();
    
    codegen.initialize_package_integration(package_manager, package_config).unwrap();
    
    // Test symbol resolution (should be empty initially)
    assert!(!codegen.has_package_symbol("non_existent_symbol"));
    assert!(codegen.get_package_symbols().is_empty());
    
    let stats = codegen.get_package_stats();
    assert!(stats.is_some());
    
    let stats = stats.unwrap();
    assert_eq!(stats.compiled_modules, 0);
    assert_eq!(stats.available_symbols, 0);
}

#[tokio::test]
async fn test_package_integration_trait() {
    // Test the LlvmPackageIntegration trait implementation
    let mut codegen = LlvmCodeGenerator::new().unwrap();
    
    let source = r#"
slay main() {
    capicola("Hello from trait!");
}
"#;
    
    // This should work with the trait implementation
    let result = codegen.compile_with_auto_packages(source, None).await;
    assert!(result.is_ok());
    
    let ir = result.unwrap();
    assert!(ir.contains("Generated by CURSED Compiler with Package Integration"));
}

#[tokio::test]
async fn test_package_installation() {
    // Create package manager
    let package_manager_config = PackageManagerConfig::default();
    let package_manager = Arc::new(Mutex::new(
        PackageManager::new(package_manager_config).unwrap()
    ));
    
    // Create LLVM code generator with package integration
    let mut codegen = LlvmCodeGenerator::new().unwrap();
    let package_config = LlvmPackageConfig::default();
    
    codegen.initialize_package_integration(package_manager, package_config).unwrap();
    
    // Try to install a non-existent package (should fail gracefully)
    let result = codegen.install_package("non_existent_package").await;
    assert!(result.is_err());
}

#[tokio::test]
async fn test_validation_without_package_integration() {
    // Test that compilation works without package integration
    let mut codegen = LlvmCodeGenerator::new().unwrap();
    
    let source = r#"
slay main() {
    capicola("Hello without packages!");
}
"#;
    
    // Should fall back to regular compilation
    let result = codegen.compile_with_packages(source, None).await;
    assert!(result.is_ok());
    
    let ir = result.unwrap();
    assert!(ir.contains("Generated by CURSED Compiler"));
    
    // Package methods should return default values
    assert!(!codegen.package_integration_enabled());
    assert!(!codegen.has_package_symbol("any_symbol"));
    assert!(codegen.get_package_symbols().is_empty());
    assert!(codegen.get_package_stats().is_none());
}

#[tokio::test] 
async fn test_resolve_package_import_without_integration() {
    let mut codegen = LlvmCodeGenerator::new().unwrap();
    
    // Should fail without package integration
    let result = codegen.resolve_package_import("stdlib::io").await;
    assert!(result.is_err());
    assert!(result.unwrap_err().to_string().contains("Package integration not initialized"));
}

#[tokio::test]
async fn test_lib_rs_integration() {
    // Test the main lib.rs functions work with package integration
    
    let source = r#"
slay main() {
    capicola("Testing lib.rs integration!");
}
"#;
    
    // Test compile_to_ir_with_packages
    let result = cursed::compile_to_ir_with_packages(source, None);
    assert!(result.is_ok());
    
    let ir = result.unwrap();
    assert!(ir.contains("Generated by CURSED Compiler with Package Integration"));
    
    // Test check_with_packages  
    let result = cursed::check_with_packages(source, None);
    assert!(result.is_ok());
    
    // Test run_with_packages
    let result = cursed::run_with_packages(source, None);
    assert!(result.is_ok());
}

#[cfg(test)]
mod helper_tests {
    use super::*;
    use cursed::ast::ImportStatement;
    
    #[test]
    fn test_import_validation() {
        let mut codegen = LlvmCodeGenerator::new().unwrap();
        
        // Valid imports
        let valid_imports = vec![
            ImportStatement {
                token: cursed::lexer::Token::new(cursed::lexer::TokenType::Identifier, "stdlib::io"),
                path: "stdlib::io".to_string(),
                alias: None,
            },
            ImportStatement {
                token: cursed::lexer::Token::new(cursed::lexer::TokenType::Identifier, "package::module"),
                path: "package::module".to_string(),
                alias: None,
            },
        ];
        
        let result = codegen.validate_package_dependencies(&valid_imports);
        assert!(result.is_ok());
        
        // Invalid imports
        let invalid_imports = vec![
            ImportStatement {
                token: cursed::lexer::Token::new(cursed::lexer::TokenType::Identifier, ""),
                path: "".to_string(), // Empty path
                alias: None,
            },
        ];
        
        let result = codegen.validate_package_dependencies(&invalid_imports);
        assert!(result.is_err());
    }
}
