#[cfg(test)]
mod tests {
    use cursed::codegen::llvm::{
        LlvmCodeGenerator, ControlFlowCompilation, LlvmControlFlowCompiler, 
        ControlFlowContext, LoopContext
    };
    use cursed::ast::expressions::{Literal, LiteralValue, Identifier};
    use cursed::ast::statements::control_flow::{
        LowkeyStatement, HighkeyStatement, PerioddtStatement, BestieStatement,
        FlexStatement, VibeCheckStatement, MoodStatement, BasicStatement
    };
    use cursed::ast::tokens::Token;
    use cursed::ast::Expression;
    use cursed::error::Error;

    #[path = "common.rs"]
    mod common;

    // Helper function to create a simple literal expression
    fn create_literal_expression(value: i32) -> Box<dyn Expression> {
        Box::new(Literal {
            value: LiteralValue::Integer(value as i64),
        })
    }

    // Helper function to create a boolean literal expression
    fn create_bool_expression(value: bool) -> Box<dyn Expression> {
        Box::new(Literal {
            value: LiteralValue::Boolean(value),
        })
    }

    // Helper function to create an identifier expression
    fn create_identifier_expression(name: &str) -> Box<dyn Expression> {
        Box::new(Identifier {
            name: Token::new_identifier(name.to_string(), 1, 1),
        })
    }

    #[test]
    fn test_llvm_code_generator_creation() {
        common::tracing::setup();
        
        let generator = LlvmCodeGenerator::new();
        assert!(generator.is_ok(), "Should create LLVM code generator successfully");
        
        let gen = generator.unwrap();
        println!("Successfully created LLVM code generator");
        
        // Test basic IR generation
        let ir_result = gen.generate_ir("// Basic test");
        assert!(ir_result.is_ok(), "Should generate basic IR");
        
        let ir = ir_result.unwrap();
        assert!(!ir.is_empty(), "Generated IR should not be empty");
        assert!(ir.contains("Generated by CURSED Compiler"), "Should contain compiler signature");
    }

    #[test]
    fn test_control_flow_context_creation() {
        common::tracing::setup();
        
        let context = ControlFlowContext::new("test_function".to_string());
        assert_eq!(context.function_name(), "test_function");
        assert!(!context.is_in_loop());
        assert_eq!(context.break_depth(), 0);
        assert_eq!(context.continue_depth(), 0);
    }

    #[test]
    fn test_loop_context_creation() {
        common::tracing::setup();
        
        let loop_context = LoopContext::new("for_loop".to_string(), "loop_body".to_string());
        assert_eq!(loop_context.loop_type(), "for_loop");
        assert_eq!(loop_context.loop_label(), "loop_body");
        assert!(!loop_context.has_break());
        assert!(!loop_context.has_continue());
    }

    #[test]
    fn test_lowkey_statement_compilation() {
        common::tracing::setup();
        
        // Create a lowkey (if) statement: lowkey (true) { ... }
        let condition = create_bool_expression(true);
        let then_body = vec![];
        let else_body = None;
        
        let lowkey_stmt = LowkeyStatement {
            condition,
            then_body,
            else_body,
        };
        
        let mut generator = LlvmCodeGenerator::new().expect("Should create generator");
        let mut context = ControlFlowContext::new("test_if".to_string());
        
        let result = generator.compile_if_statement(&lowkey_stmt, &mut context);
        
        match result {
            Ok(()) => {
                println!("Successfully compiled lowkey (if) statement");
            }
            Err(e) => {
                println!("Lowkey statement compilation failed (may be expected): {}", e);
                // This might fail due to missing dependencies, which is normal for this test
            }
        }
    }

    #[test]
    fn test_highkey_statement_compilation() {
        common::tracing::setup();
        
        // Create a highkey (else if) statement
        let condition = create_bool_expression(false);
        let then_body = vec![];
        
        let highkey_stmt = HighkeyStatement {
            condition,
            then_body,
        };
        
        let mut generator = LlvmCodeGenerator::new().expect("Should create generator");
        let mut context = ControlFlowContext::new("test_else_if".to_string());
        
        let result = generator.compile_else_if_statement(&highkey_stmt, &mut context);
        
        match result {
            Ok(()) => {
                println!("Successfully compiled highkey (else if) statement");
            }
            Err(e) => {
                println!("Highkey statement compilation failed (may be expected): {}", e);
            }
        }
    }

    #[test]
    fn test_periodt_statement_compilation() {
        common::tracing::setup();
        
        // Create a periodt (else) statement
        let else_body = vec![];
        
        let periodt_stmt = PerioddtStatement {
            else_body,
        };
        
        let mut generator = LlvmCodeGenerator::new().expect("Should create generator");
        let mut context = ControlFlowContext::new("test_else".to_string());
        
        let result = generator.compile_else_statement(&periodt_stmt, &mut context);
        
        match result {
            Ok(()) => {
                println!("Successfully compiled periodt (else) statement");
            }
            Err(e) => {
                println!("Periodt statement compilation failed (may be expected): {}", e);
            }
        }
    }

    #[test]
    fn test_bestie_statement_compilation() {
        common::tracing::setup();
        
        // Create a bestie (for) loop statement
        use cursed::ast::statements::LetStatement;
        
        let init = Some(Box::new(LetStatement {
            name: Token::new_identifier("i".to_string(), 1, 5),
            value: Some(create_literal_expression(0)),
            type_annotation: None,
            is_mutable: true,
        }) as Box<dyn cursed::ast::Statement>);
        
        let condition = Some(create_bool_expression(true));
        let increment = Some(create_identifier_expression("i"));
        let body = vec![];
        
        let bestie_stmt = BestieStatement {
            init,
            condition,
            increment,
            body,
        };
        
        let mut generator = LlvmCodeGenerator::new().expect("Should create generator");
        let mut context = ControlFlowContext::new("test_for".to_string());
        
        let result = generator.compile_for_loop(&bestie_stmt, &mut context);
        
        match result {
            Ok(()) => {
                println!("Successfully compiled bestie (for) loop");
            }
            Err(e) => {
                println!("Bestie loop compilation failed (may be expected): {}", e);
            }
        }
    }

    #[test]
    fn test_flex_statement_compilation() {
        common::tracing::setup();
        
        // Create a flex (while) loop statement
        let condition = create_bool_expression(true);
        let body = vec![];
        
        let flex_stmt = FlexStatement {
            condition,
            body,
        };
        
        let mut generator = LlvmCodeGenerator::new().expect("Should create generator");
        let mut context = ControlFlowContext::new("test_while".to_string());
        
        let result = generator.compile_while_loop(&flex_stmt, &mut context);
        
        match result {
            Ok(()) => {
                println!("Successfully compiled flex (while) loop");
            }
            Err(e) => {
                println!("Flex loop compilation failed (may be expected): {}", e);
            }
        }
    }

    #[test]
    fn test_vibe_check_statement_compilation() {
        common::tracing::setup();
        
        // Create a vibe_check (switch) statement
        let expression = create_identifier_expression("value");
        let moods = vec![];
        let basic_case = None;
        
        let vibe_check_stmt = VibeCheckStatement {
            expression,
            moods,
            basic_case,
        };
        
        let mut generator = LlvmCodeGenerator::new().expect("Should create generator");
        let mut context = ControlFlowContext::new("test_switch".to_string());
        
        let result = generator.compile_switch_statement(&vibe_check_stmt, &mut context);
        
        match result {
            Ok(()) => {
                println!("Successfully compiled vibe_check (switch) statement");
            }
            Err(e) => {
                println!("Vibe check compilation failed (may be expected): {}", e);
            }
        }
    }

    #[test]
    fn test_mood_case_compilation() {
        common::tracing::setup();
        
        // Create a mood (case) statement
        let values = vec![create_literal_expression(1), create_literal_expression(2)];
        let body = vec![];
        
        let mood_stmt = MoodStatement {
            values,
            body,
        };
        
        let mut generator = LlvmCodeGenerator::new().expect("Should create generator");
        let mut context = ControlFlowContext::new("test_case".to_string());
        
        let result = generator.compile_case_statement(&mood_stmt, &mut context);
        
        match result {
            Ok(()) => {
                println!("Successfully compiled mood (case) statement");
            }
            Err(e) => {
                println!("Mood case compilation failed (may be expected): {}", e);
            }
        }
    }

    #[test]
    fn test_basic_default_compilation() {
        common::tracing::setup();
        
        // Create a basic (default) case statement
        let body = vec![];
        
        let basic_stmt = BasicStatement {
            body,
        };
        
        let mut generator = LlvmCodeGenerator::new().expect("Should create generator");
        let mut context = ControlFlowContext::new("test_default".to_string());
        
        let result = generator.compile_default_case(&basic_stmt, &mut context);
        
        match result {
            Ok(()) => {
                println!("Successfully compiled basic (default) case");
            }
            Err(e) => {
                println!("Basic default compilation failed (may be expected): {}", e);
            }
        }
    }

    #[test]
    fn test_nested_control_flow() {
        common::tracing::setup();
        
        let mut generator = LlvmCodeGenerator::new().expect("Should create generator");
        let mut context = ControlFlowContext::new("test_nested".to_string());
        
        // Test nested if statements
        let outer_condition = create_bool_expression(true);
        let inner_condition = create_bool_expression(false);
        
        // Create inner if statement
        let inner_if = LowkeyStatement {
            condition: inner_condition,
            then_body: vec![],
            else_body: None,
        };
        
        // Create outer if statement with inner if in body
        let outer_if = LowkeyStatement {
            condition: outer_condition,
            then_body: vec![], // In real code, this would contain the inner_if
            else_body: None,
        };
        
        // Test compilation of nested structure
        let result1 = generator.compile_if_statement(&outer_if, &mut context);
        let result2 = generator.compile_if_statement(&inner_if, &mut context);
        
        match (result1, result2) {
            (Ok(()), Ok(())) => {
                println!("Successfully compiled nested control flow");
            }
            (Err(e1), _) => {
                println!("Outer if compilation failed: {}", e1);
            }
            (_, Err(e2)) => {
                println!("Inner if compilation failed: {}", e2);
            }
        }
    }

    #[test]
    fn test_loop_with_break_continue() {
        common::tracing::setup();
        
        let mut generator = LlvmCodeGenerator::new().expect("Should create generator");
        let mut context = ControlFlowContext::new("test_loop_control".to_string());
        
        // Create a loop context
        let loop_ctx = LoopContext::new("while_loop".to_string(), "main_loop".to_string());
        context.enter_loop(loop_ctx);
        
        // Test break compilation
        let break_result = generator.compile_break(&mut context);
        match break_result {
            Ok(()) => {
                println!("Successfully compiled break statement");
            }
            Err(e) => {
                println!("Break compilation failed (may be expected): {}", e);
            }
        }
        
        // Test continue compilation
        let continue_result = generator.compile_continue(&mut context);
        match continue_result {
            Ok(()) => {
                println!("Successfully compiled continue statement");
            }
            Err(e) => {
                println!("Continue compilation failed (may be expected): {}", e);
            }
        }
        
        // Exit loop context
        context.exit_loop();
        assert!(!context.is_in_loop());
    }

    #[test]
    fn test_control_flow_error_handling() {
        common::tracing::setup();
        
        let mut generator = LlvmCodeGenerator::new().expect("Should create generator");
        let mut context = ControlFlowContext::new("test_errors".to_string());
        
        // Test break outside of loop (should fail)
        let break_outside_loop = generator.compile_break(&mut context);
        assert!(break_outside_loop.is_err(), "Break outside loop should fail");
        
        // Test continue outside of loop (should fail)
        let continue_outside_loop = generator.compile_continue(&mut context);
        assert!(continue_outside_loop.is_err(), "Continue outside loop should fail");
        
        println!("Error handling for control flow works correctly");
    }

    #[test]
    fn test_complex_switch_case() {
        common::tracing::setup();
        
        let mut generator = LlvmCodeGenerator::new().expect("Should create generator");
        let mut context = ControlFlowContext::new("test_complex_switch".to_string());
        
        // Create multiple mood (case) statements
        let mood1 = MoodStatement {
            values: vec![create_literal_expression(1)],
            body: vec![],
        };
        
        let mood2 = MoodStatement {
            values: vec![create_literal_expression(2), create_literal_expression(3)],
            body: vec![],
        };
        
        let basic_case = BasicStatement {
            body: vec![],
        };
        
        // Create vibe_check (switch) with multiple cases
        let vibe_check = VibeCheckStatement {
            expression: create_identifier_expression("x"),
            moods: vec![mood1, mood2],
            basic_case: Some(basic_case),
        };
        
        let result = generator.compile_switch_statement(&vibe_check, &mut context);
        
        match result {
            Ok(()) => {
                println!("Successfully compiled complex switch statement");
            }
            Err(e) => {
                println!("Complex switch compilation failed (may be expected): {}", e);
            }
        }
    }

    #[test]
    fn test_control_flow_optimization() {
        common::tracing::setup();
        
        let mut generator = LlvmCodeGenerator::new().expect("Should create generator");
        
        // Enable optimizations
        assert!(generator.optimization_enabled());
        
        let mut context = ControlFlowContext::new("test_optimization".to_string());
        
        // Test if statement with constant condition (should be optimized)
        let constant_true_if = LowkeyStatement {
            condition: create_bool_expression(true),
            then_body: vec![],
            else_body: None,
        };
        
        let result = generator.compile_if_statement(&constant_true_if, &mut context);
        
        match result {
            Ok(()) => {
                println!("Compiled if statement with constant condition (may be optimized)");
            }
            Err(e) => {
                println!("Constant condition if compilation failed: {}", e);
            }
        }
        
        // Test if statement with constant false condition
        let constant_false_if = LowkeyStatement {
            condition: create_bool_expression(false),
            then_body: vec![],
            else_body: Some(vec![]),
        };
        
        let result = generator.compile_if_statement(&constant_false_if, &mut context);
        
        match result {
            Ok(()) => {
                println!("Compiled if statement with false condition (may be optimized away)");
            }
            Err(e) => {
                println!("False condition if compilation failed: {}", e);
            }
        }
    }

    #[test]
    fn test_control_flow_debug_info() {
        common::tracing::setup();
        
        let mut generator = LlvmCodeGenerator::new().expect("Should create generator");
        
        // Test debug information generation for control flow
        if generator.debug_enabled() {
            let debug_stats = generator.debug_statistics();
            println!("Debug statistics: {}", debug_stats);
        }
        
        let mut context = ControlFlowContext::new("test_debug".to_string());
        
        // Compile a simple if statement
        let if_stmt = LowkeyStatement {
            condition: create_bool_expression(true),
            then_body: vec![],
            else_body: None,
        };
        
        let result = generator.compile_if_statement(&if_stmt, &mut context);
        
        match result {
            Ok(()) => {
                println!("Compiled control flow with debug information");
                
                // Check line table if debug is enabled
                if generator.debug_enabled() {
                    let line_table = generator.line_table();
                    println!("Generated {} debug line entries", line_table.len());
                }
            }
            Err(e) => {
                println!("Debug control flow compilation failed: {}", e);
            }
        }
    }

    #[test]
    fn test_control_flow_ir_generation() {
        common::tracing::setup();
        
        let mut generator = LlvmCodeGenerator::new().expect("Should create generator");
        
        // Generate IR for a program with control flow
        let cursed_code = r#"
slay main() {
    sus x = 5;
    lowkey (x > 0) {
        x = x - 1;
    } periodt {
        x = 0;
    }
    brrr x;
}
"#;
        
        let ir_result = generator.generate_ir(cursed_code);
        
        match ir_result {
            Ok(ir) => {
                println!("Successfully generated IR for control flow program");
                println!("IR length: {} characters", ir.len());
                
                // Verify IR contains expected elements
                assert!(ir.contains("Generated by CURSED Compiler"), "Should contain compiler signature");
                
                // The IR should contain some LLVM constructs
                // Note: Actual control flow compilation might not be fully implemented
                // so we just verify basic IR generation works
                
                if ir.contains("define") {
                    println!("IR contains function definitions");
                }
                
                if ir.contains("br") || ir.contains("switch") {
                    println!("IR contains control flow instructions");
                }
            }
            Err(e) => {
                println!("IR generation failed: {}", e);
            }
        }
    }
}
