/// Real LLVM integration tests for the CURSED compiler
/// 
/// These tests validate that the CURSED compiler can generate actual 
/// executable LLVM IR using real inkwell types instead of placeholders.

use cursed::codegen::llvm::LlvmCodeGenerator;
use cursed::ast::{
    Program,
    declarations::FunctionStatement,
    statements::LetStatement,
    expressions::{Literal, LiteralValue, Parameter},
    identifiers::{Identifier, Token},
    parser_support::VariableStatement,
};
use cursed::error::Error;
use cursed::runtime::Runtime;
use std::sync::Arc;

#[path = "common.rs"]
mod common;

#[test]
fn test_real_llvm_code_generator_creation() {
    common::tracing::setup();
    
    let result = LlvmCodeGenerator::new();
    assert!(result.is_ok(), "Failed to create real LLVM code generator: {:?}", result.err());
    
    let generator = result.unwrap();
    
    // Verify that real LLVM components were created
    assert!(generator.get_context().is_some(), "LLVM context should be available");
    assert!(generator.get_module().strong_count() > 0, "LLVM module should be available");
    assert!(generator.get_builder().strong_count() > 0, "LLVM builder should be available");
    assert!(generator.get_runtime().is_some(), "Runtime should be available");
}

#[test]
fn test_real_llvm_ir_generation() {
    common::tracing::setup();
    
    let mut generator = LlvmCodeGenerator::new().expect("Failed to create generator");
    
    // Generate IR for a simple program
    let source = "slay main() { yolo 0; }";
    let ir_result = generator.generate_ir(source);
    
    assert!(ir_result.is_ok(), "Failed to generate IR: {:?}", ir_result.err());
    
    let ir = ir_result.unwrap();
    
    // Verify the IR contains expected elements
    assert!(ir.contains("Generated by CURSED Compiler"), "IR should contain compiler signature");
    assert!(ir.contains("define"), "IR should contain function definitions");
    assert!(ir.contains("main"), "IR should contain main function");
    assert!(ir.contains("ret"), "IR should contain return instruction");
    
    println!("Generated LLVM IR:\n{}", ir);
}

#[test]
fn test_real_literal_compilation() {
    common::tracing::setup();
    
    let generator = LlvmCodeGenerator::new().expect("Failed to create generator");
    
    // Test integer literal
    let int_literal = Literal {
        value: LiteralValue::Integer(42),
    };
    
    let result = generator.compile_literal_real(&int_literal);
    assert!(result.is_ok(), "Failed to compile integer literal: {:?}", result.err());
    
    let llvm_value = result.unwrap();
    assert_eq!(llvm_value.llvm_name, "42");
    assert!(llvm_value.is_constant);
    
    // Test string literal
    let string_literal = Literal {
        value: LiteralValue::String("Hello, CURSED!".to_string()),
    };
    
    let result = generator.compile_literal_real(&string_literal);
    assert!(result.is_ok(), "Failed to compile string literal: {:?}", result.err());
    
    let llvm_value = result.unwrap();
    assert!(llvm_value.llvm_name.starts_with("@str_"));
    assert!(llvm_value.is_constant);
    
    // Test boolean literal
    let bool_literal = Literal {
        value: LiteralValue::Boolean(true),
    };
    
    let result = generator.compile_literal_real(&bool_literal);
    assert!(result.is_ok(), "Failed to compile boolean literal: {:?}", result.err());
    
    let llvm_value = result.unwrap();
    assert_eq!(llvm_value.llvm_name, "true");
    assert!(llvm_value.is_constant);
}

#[test]
fn test_real_function_compilation() {
    common::tracing::setup();
    
    let generator = LlvmCodeGenerator::new().expect("Failed to create generator");
    
    // Create a simple function: slay add(a: normie, b: normie) -> normie { yolo a + b; }
    let function = FunctionStatement {
        name: Identifier {
            value: "add".to_string(),
            token: Token::new("add", 1, 1),
        },
        parameters: vec![
            Parameter {
                name: Identifier {
                    value: "a".to_string(),
                    token: Token::new("a", 1, 9),
                },
                param_type: Some(Box::new(Identifier {
                    value: "normie".to_string(),
                    token: Token::new("normie", 1, 12),
                })),
            },
            Parameter {
                name: Identifier {
                    value: "b".to_string(),
                    token: Token::new("b", 1, 20),
                },
                param_type: Some(Box::new(Identifier {
                    value: "normie".to_string(),
                    token: Token::new("normie", 1, 23),
                })),
            },
        ],
        return_type: Some(Box::new(Identifier {
            value: "normie".to_string(),
            token: Token::new("normie", 1, 33),
        })),
        body: None, // Simplified for now
        generics: Vec::new(),
        constraints: Vec::new(),
    };
    
    let result = generator.compile_function_real(&function);
    assert!(result.is_ok(), "Failed to compile function: {:?}", result.err());
    
    let llvm_function = result.unwrap();
    
    // Verify function properties
    assert_eq!(llvm_function.get_name().to_str().unwrap(), "add");
    assert_eq!(llvm_function.count_params(), 2);
    
    // Verify function passes LLVM verification
    assert!(llvm_function.verify(true), "Function should pass LLVM verification");
}

#[test]
fn test_real_variable_compilation() {
    common::tracing::setup();
    
    let generator = LlvmCodeGenerator::new().expect("Failed to create generator");
    
    // First, we need to create a function context to compile variables in
    // Create a simple main function first
    let main_function = FunctionStatement {
        name: Identifier {
            value: "main".to_string(),
            token: Token::new("main", 1, 1),
        },
        parameters: vec![],
        return_type: Some(Box::new(Identifier {
            value: "normie".to_string(),
            token: Token::new("normie", 1, 10),
        })),
        body: None,
        generics: Vec::new(),
        constraints: Vec::new(),
    };
    
    // Compile the function to create a context
    let function_result = generator.compile_function_real(&main_function);
    assert!(function_result.is_ok(), "Failed to create function context");
    
    // Now test variable compilation: sus x = 42;
    let variable = LetStatement {
        name: Identifier {
            value: "x".to_string(),
            token: Token::new("x", 1, 5),
        },
        value: Some(Box::new(Literal {
            value: LiteralValue::Integer(42),
        })),
        type_annotation: Some(Box::new(Identifier {
            value: "normie".to_string(),
            token: Token::new("normie", 1, 8),
        })),
        is_mutable: true,
    };
    
    let result = generator.compile_variable_declaration_real(&variable);
    assert!(result.is_ok(), "Failed to compile variable: {:?}", result.err());
}

#[test]
fn test_real_program_compilation() {
    common::tracing::setup();
    
    let mut generator = LlvmCodeGenerator::new().expect("Failed to create generator");
    
    // Create a simple program with a main function
    let program = Program {
        package_name: Some("test_package".to_string()),
        imports: vec![],
        statements: vec![
            Box::new(FunctionStatement {
                name: Identifier {
                    value: "main".to_string(),
                    token: Token::new("main", 1, 1),
                },
                parameters: vec![],
                return_type: Some(Box::new(Identifier {
                    value: "normie".to_string(),
                    token: Token::new("normie", 1, 10),
                })),
                body: None,
                generics: Vec::new(),
                constraints: Vec::new(),
            }),
        ],
    };
    
    let result = generator.compile(&program);
    assert!(result.is_ok(), "Failed to compile program: {:?}", result.err());
    
    // Generate IR and verify it's valid
    let ir_result = generator.generate_ir("slay main() -> normie { yolo 0; }");
    assert!(ir_result.is_ok(), "Failed to generate IR after compilation");
    
    let ir = ir_result.unwrap();
    assert!(ir.contains("define"), "Compiled IR should contain function definitions");
    assert!(ir.contains("main"), "Compiled IR should contain main function");
    
    println!("Compiled program IR:\n{}", ir);
}

#[test]
fn test_llvm_type_conversion() {
    common::tracing::setup();
    
    let generator = LlvmCodeGenerator::new().expect("Failed to create generator");
    
    // Test various CURSED type to LLVM type conversions
    let test_cases = vec![
        ("normie", "i32"),
        ("sus", "i32"),
        ("i64", "i64"), 
        ("facts", "i1"),
        ("bool", "i1"),
        ("vibes", "f64"),
        ("f64", "f64"),
        ("double", "f64"),
        ("tea", "i8*"),
        ("string", "i8*"),
    ];
    
    for (cursed_type, expected_llvm) in test_cases {
        let result = generator.cursed_type_to_llvm_type(cursed_type);
        assert!(result.is_ok(), "Failed to convert type {}: {:?}", cursed_type, result.err());
        
        let llvm_type = result.unwrap();
        
        // Verify the type is correct (simplified check)
        match expected_llvm {
            "i32" => assert!(llvm_type.is_int_type(), "Expected i32 type for {}", cursed_type),
            "i64" => assert!(llvm_type.is_int_type(), "Expected i64 type for {}", cursed_type),
            "i1" => assert!(llvm_type.is_int_type(), "Expected i1 type for {}", cursed_type),
            "f64" => assert!(llvm_type.is_float_type(), "Expected f64 type for {}", cursed_type),
            "i8*" => assert!(llvm_type.is_pointer_type(), "Expected pointer type for {}", cursed_type),
            _ => panic!("Unknown expected type: {}", expected_llvm),
        }
    }
}

#[test]
fn test_llvm_module_verification() {
    common::tracing::setup();
    
    let mut generator = LlvmCodeGenerator::new().expect("Failed to create generator");
    
    // Create a valid program
    let program = Program {
        package_name: Some("verification_test".to_string()),
        imports: vec![],
        statements: vec![
            Box::new(FunctionStatement {
                name: Identifier {
                    value: "test_function".to_string(),
                    token: Token::new("test_function", 1, 1),
                },
                parameters: vec![],
                return_type: Some(Box::new(Identifier {
                    value: "normie".to_string(),
                    token: Token::new("normie", 1, 16),
                })),
                body: None,
                generics: Vec::new(),
                constraints: Vec::new(),
            }),
        ],
    };
    
    // Compile the program
    let compile_result = generator.compile(&program);
    assert!(compile_result.is_ok(), "Failed to compile program for verification");
    
    // Verify the module
    let module_guard = generator.get_module().lock().expect("Failed to acquire module lock");
    let verification_result = module_guard.verify();
    
    assert!(verification_result.is_ok(), "Module failed verification: {:?}", verification_result.err());
}

#[test]
fn test_optimization_integration() {
    common::tracing::setup();
    
    let mut generator = LlvmCodeGenerator::new().expect("Failed to create generator");
    
    // Verify optimization is enabled by default
    assert!(generator.optimization_enabled(), "Optimization should be enabled by default");
    
    // Test disabling optimization
    generator.disable_optimization();
    assert!(!generator.optimization_enabled(), "Optimization should be disabled");
    
    // Test re-enabling optimization
    let optimization_config = cursed::optimization::OptimizationConfig::default();
    let enable_result = generator.enable_optimization(optimization_config);
    assert!(enable_result.is_ok(), "Failed to enable optimization: {:?}", enable_result.err());
    assert!(generator.optimization_enabled(), "Optimization should be enabled again");
}

#[test]
fn test_runtime_integration() {
    common::tracing::setup();
    
    // Create generator with custom runtime
    let runtime = Runtime::new().expect("Failed to create runtime");
    let runtime_arc = Arc::new(runtime);
    
    let generator_result = LlvmCodeGenerator::new_with_runtime(runtime_arc.clone());
    assert!(generator_result.is_ok(), "Failed to create generator with runtime");
    
    let generator = generator_result.unwrap();
    
    // Verify runtime integration
    let generator_runtime = generator.get_runtime();
    assert!(Arc::ptr_eq(&runtime_arc, &generator_runtime), "Runtime should be the same instance");
}
