use cursed::stdlib::packages::crypto_random::*;
use std::collections::HashSet;
use std::thread;
use std::sync::Arc;

#[test]
fn test_fill_random_basic() {
    let mut buffer = [0u8; 32];
    let result = fill_random(&mut buffer);
    
    assert!(result.is_ok(), "fill_random should succeed");
    
    // Verify we didn't get all zeros (old stub behavior)
    assert_ne!(buffer, [0u8; 32], "Buffer should not be all zeros");
    
    // Verify buffer was actually filled with different values
    let unique_values: HashSet<u8> = buffer.iter().cloned().collect();
    assert!(unique_values.len() > 1, "Buffer should contain varied random data");
}

#[test]
fn test_fill_random_empty_buffer() {
    let mut buffer = [];
    let result = fill_random(&mut buffer);
    assert!(result.is_ok(), "fill_random with empty buffer should succeed");
}

#[test]
fn test_generate_random_bytes_basic() {
    let result = generate_random_bytes(32);
    assert!(result.is_ok(), "generate_random_bytes should succeed");
    
    let bytes = result.unwrap();
    assert_eq!(bytes.len(), 32, "Should generate exactly 32 bytes");
    
    // Verify we didn't get all zeros
    assert_ne!(bytes, vec![0u8; 32], "Generated bytes should not be all zeros");
    
    // Verify varied content
    let unique_values: HashSet<u8> = bytes.iter().cloned().collect();
    assert!(unique_values.len() > 1, "Generated bytes should contain varied random data");
}

#[test]
fn test_generate_random_bytes_zero_length() {
    let result = generate_random_bytes(0);
    assert!(result.is_ok(), "generate_random_bytes(0) should succeed");
    
    let bytes = result.unwrap();
    assert_eq!(bytes.len(), 0, "Should generate empty vector for zero length");
}

#[test]
fn test_generate_random_bytes_large_size() {
    // Test a reasonably large size
    let result = generate_random_bytes(8192);
    assert!(result.is_ok(), "generate_random_bytes should succeed for 8KB");
    
    let bytes = result.unwrap();
    assert_eq!(bytes.len(), 8192, "Should generate exactly 8192 bytes");
    
    // Verify randomness with larger sample
    let unique_values: HashSet<u8> = bytes.iter().cloned().collect();
    assert!(unique_values.len() > 200, "Large sample should have good byte distribution");
}

#[test]
fn test_generate_random_bytes_maximum_size() {
    // Test maximum allowed size (1MB)
    let result = generate_random_bytes(1024 * 1024);
    assert!(result.is_ok(), "generate_random_bytes should succeed for 1MB");
    
    let bytes = result.unwrap();
    assert_eq!(bytes.len(), 1024 * 1024, "Should generate exactly 1MB");
}

#[test]
fn test_generate_random_bytes_oversized() {
    // Test size above limit
    let result = generate_random_bytes(1024 * 1024 + 1);
    assert!(result.is_err(), "generate_random_bytes should fail for size > 1MB");
    
    let error = result.unwrap_err();
    assert!(error.contains("exceeds maximum"), "Error should mention size limit");
}

#[test]
fn test_generate_random_u32() {
    let result = generate_random_u32();
    assert!(result.is_ok(), "generate_random_u32 should succeed");
    
    let value = result.unwrap();
    
    // Generate multiple values to ensure they're different
    let mut values = HashSet::new();
    values.insert(value);
    
    for _ in 0..10 {
        let next_result = generate_random_u32();
        assert!(next_result.is_ok(), "All generate_random_u32 calls should succeed");
        values.insert(next_result.unwrap());
    }
    
    // With high probability, we should get different values
    assert!(values.len() > 1, "Should generate varied u32 values");
}

#[test]
fn test_generate_random_u64() {
    let result = generate_random_u64();
    assert!(result.is_ok(), "generate_random_u64 should succeed");
    
    let value = result.unwrap();
    
    // Generate multiple values to ensure they're different
    let mut values = HashSet::new();
    values.insert(value);
    
    for _ in 0..10 {
        let next_result = generate_random_u64();
        assert!(next_result.is_ok(), "All generate_random_u64 calls should succeed");
        values.insert(next_result.unwrap());
    }
    
    // With high probability, we should get different values
    assert!(values.len() > 1, "Should generate varied u64 values");
}

#[test]
fn test_generate_random_bool() {
    let mut true_count = 0;
    let mut false_count = 0;
    
    // Generate many booleans and check distribution
    for _ in 0..1000 {
        let result = generate_random_bool();
        assert!(result.is_ok(), "generate_random_bool should succeed");
        
        if result.unwrap() {
            true_count += 1;
        } else {
            false_count += 1;
        }
    }
    
    // Both true and false should appear (very high probability)
    assert!(true_count > 0, "Should generate some true values");
    assert!(false_count > 0, "Should generate some false values");
    
    // Distribution should be roughly even (allowing for variance)
    let ratio = true_count as f64 / 1000.0;
    assert!(ratio > 0.3 && ratio < 0.7, "Boolean distribution should be roughly even");
}

#[test]
fn test_generate_random_range() {
    let min = 10u32;
    let max = 50u32;
    
    let mut values = HashSet::new();
    
    for _ in 0..100 {
        let result = generate_random_range(min, max);
        assert!(result.is_ok(), "generate_random_range should succeed");
        
        let value = result.unwrap();
        assert!(value >= min && value < max, "Value should be in range [min, max)");
        values.insert(value);
    }
    
    // Should generate multiple different values in the range
    assert!(values.len() > 1, "Should generate varied values in range");
}

#[test]
fn test_generate_random_range_invalid() {
    // Test invalid range where min >= max
    let result = generate_random_range(50, 50);
    assert!(result.is_err(), "generate_random_range should fail for min == max");
    
    let result = generate_random_range(50, 30);
    assert!(result.is_err(), "generate_random_range should fail for min > max");
}

#[test]
fn test_generate_random_hex() {
    let result = generate_random_hex(16);
    assert!(result.is_ok(), "generate_random_hex should succeed");
    
    let hex_string = result.unwrap();
    assert_eq!(hex_string.len(), 32, "Hex string should be 2x input length");
    
    // Verify it's valid hex
    assert!(hex_string.chars().all(|c| c.is_ascii_hexdigit()), "Should be valid hex");
    
    // Verify it's not all zeros
    assert_ne!(hex_string, "0".repeat(32), "Hex string should not be all zeros");
}

#[test]
fn test_generate_random_base64() {
    let result = generate_random_base64(16);
    assert!(result.is_ok(), "generate_random_base64 should succeed");
    
    let b64_string = result.unwrap();
    
    // Base64 encoding increases size by ~4/3
    assert!(b64_string.len() > 16, "Base64 string should be longer than input");
    
    // Verify it's valid base64 by trying to decode
    let decode_result = base64::decode(&b64_string);
    assert!(decode_result.is_ok(), "Generated string should be valid base64");
    
    let decoded = decode_result.unwrap();
    assert_eq!(decoded.len(), 16, "Decoded data should match original length");
}

#[test]
fn test_rng_statistics() {
    // Reset statistics before test
    let reset_result = reset_rng_statistics();
    assert!(reset_result.is_ok(), "Should be able to reset statistics");
    
    // Generate some random data
    let _bytes = generate_random_bytes(100).unwrap();
    let _u32_val = generate_random_u32().unwrap();
    let _u64_val = generate_random_u64().unwrap();
    
    // Check statistics
    let stats_result = get_rng_statistics();
    assert!(stats_result.is_ok(), "Should be able to get statistics");
    
    let stats = stats_result.unwrap();
    assert!(stats.bytes_generated > 0, "Should have generated some bytes");
    assert!(stats.generation_count > 0, "Should have some generation count");
    assert_eq!(stats.errors_count, 0, "Should have no errors");
    assert!(stats.entropy_sources.contains_key("OsRng"), "Should track entropy source");
}

#[test]
fn test_entropy_quality() {
    let result = test_entropy_quality();
    assert!(result.is_ok(), "Entropy quality test should succeed");
    
    let quality_ok = result.unwrap();
    assert!(quality_ok, "Entropy quality should pass basic tests");
}

#[test]
fn test_rng_health_verification() {
    let result = verify_rng_health();
    assert!(result.is_ok(), "RNG health verification should pass: {:?}", result);
}

#[test]
fn test_thread_safety() {
    let num_threads = 8;
    let operations_per_thread = 100;
    
    let handles: Vec<_> = (0..num_threads)
        .map(|_| {
            thread::spawn(move || {
                for _ in 0..operations_per_thread {
                    // Test various operations concurrently
                    let _bytes = generate_random_bytes(32).unwrap();
                    let _u32_val = generate_random_u32().unwrap();
                    let _bool_val = generate_random_bool().unwrap();
                }
            })
        })
        .collect();
    
    // Wait for all threads to complete
    for handle in handles {
        handle.join().expect("Thread should complete successfully");
    }
    
    // Verify statistics show all operations
    let stats = get_rng_statistics().unwrap();
    let expected_operations = num_threads * operations_per_thread * 3; // 3 ops per iteration
    assert!(stats.generation_count >= expected_operations as u64, 
           "Should record all concurrent operations");
}

#[test]
fn test_randomness_distribution() {
    const SAMPLE_SIZE: usize = 10000;
    let data = generate_random_bytes(SAMPLE_SIZE).unwrap();
    
    // Count frequency of each byte value
    let mut counts = [0u32; 256];
    for &byte in &data {
        counts[byte as usize] += 1;
    }
    
    // Calculate chi-square statistic for uniformity test
    let expected = SAMPLE_SIZE as f64 / 256.0;
    let mut chi_square = 0.0;
    
    for &count in &counts {
        let diff = count as f64 - expected;
        chi_square += (diff * diff) / expected;
    }
    
    // For 255 degrees of freedom, critical value at 0.05 significance is ~293.25
    // We use a more lenient threshold since this is a basic test
    assert!(chi_square < 350.0, "Chi-square test suggests good distribution: {}", chi_square);
}

#[test]
fn test_secure_rng_struct() {
    let rng = SecureRng::new();
    assert!(rng.is_ok(), "SecureRng construction should succeed");
    
    let rng = rng.unwrap();
    
    // Test all SecureRng methods
    let mut buffer = [0u8; 16];
    assert!(rng.fill_bytes(&mut buffer).is_ok(), "fill_bytes should work");
    assert_ne!(buffer, [0u8; 16], "Buffer should be filled with random data");
    
    let bytes = rng.generate_bytes(32);
    assert!(bytes.is_ok(), "generate_bytes should work");
    assert_eq!(bytes.unwrap().len(), 32, "Should generate correct length");
    
    let u32_val = rng.next_u32();
    assert!(u32_val.is_ok(), "next_u32 should work");
    
    let u64_val = rng.next_u64();
    assert!(u64_val.is_ok(), "next_u64 should work");
    
    let bool_val = rng.next_bool();
    assert!(bool_val.is_ok(), "next_bool should work");
    
    let range_val = rng.gen_range_u32(1, 100);
    assert!(range_val.is_ok(), "gen_range_u32 should work");
    let val = range_val.unwrap();
    assert!(val >= 1 && val < 100, "Range value should be in bounds");
}

#[test]
fn test_consistency_across_calls() {
    // Multiple calls should produce different results
    let bytes1 = generate_random_bytes(32).unwrap();
    let bytes2 = generate_random_bytes(32).unwrap();
    let bytes3 = generate_random_bytes(32).unwrap();
    
    assert_ne!(bytes1, bytes2, "Consecutive calls should produce different results");
    assert_ne!(bytes2, bytes3, "Consecutive calls should produce different results");
    assert_ne!(bytes1, bytes3, "Consecutive calls should produce different results");
}
