[target.x86_64-unknown-linux-gnu]
linker = "gcc"
rustflags = [
    "-C", "linker=gcc",
    "-C", "link-arg=-fuse-ld=ld",
    "-C", "link-arg=-L/nix/store/6pak77li0iw9x0b3yhmbjvp846w3p6bx-libffi-3.4.6/lib",
    "-C", "link-arg=-L/nix/store/l5g2v1jgfyf3j0jp9iv5b79fi8yrwzpp-zlib-1.3.1/lib", 
    "-C", "link-arg=-L/nix/store/k3a7dzrqphj9ksbb43i24vy6inz8ys51-ncurses-6.4.20221231/lib",
    "-C", "link-arg=-L/nix/store/0z4hrksbdrwv9xb8ycjk3rq9ppmw0350-libxml2-2.13.5/lib",
    "-C", "link-arg=-Wl,-rpath=/nix/store/6pak77li0iw9x0b3yhmbjvp846w3p6bx-libffi-3.4.6/lib",
    "-C", "link-arg=-Wl,-rpath=/nix/store/l5g2v1jgfyf3j0jp9iv5b79fi8yrwzpp-zlib-1.3.1/lib",
    "-C", "link-arg=-Wl,-rpath=/nix/store/k3a7dzrqphj9ksbb43i24vy6inz8ys51-ncurses-6.4.20221231/lib",
    "-C", "link-arg=-Wl,-rpath=/nix/store/0z4hrksbdrwv9xb8ycjk3rq9ppmw0350-libxml2-2.13.5/lib",
    "-L", "native=/nix/store/6pak77li0iw9x0b3yhmbjvp846w3p6bx-libffi-3.4.6/lib",
    "-L", "native=/nix/store/l5g2v1jgfyf3j0jp9iv5b79fi8yrwzpp-zlib-1.3.1/lib",
    "-L", "native=/nix/store/k3a7dzrqphj9ksbb43i24vy6inz8ys51-ncurses-6.4.20221231/lib",
    "-L", "native=/nix/store/0z4hrksbdrwv9xb8ycjk3rq9ppmw0350-libxml2-2.13.5/lib"
]

[build]
target = "x86_64-unknown-linux-gnu"
