/// LLVM-based code generation with debug support
use crate::error::Error;
use crate::debug::{DebugConfig, SourceLocation};
use std::path::PathBuf;

pub mod debug_integration;
pub mod web_vibez_integration;
pub mod stdlib_registry;

pub use debug_integration::LlvmDebugCodeGenerator;
pub use web_vibez_integration::{WebVibezLlvmIntegration, HttpTypeRegistry};
pub use stdlib_registry::{StdlibRegistry, StdlibLlvmIntegration, StdlibFunction};

pub struct LlvmCodeGenerator {
    debug_generator: LlvmDebugCodeGenerator,
    module_name: Option<String>,
    web_vibez_integration: Option<WebVibezLlvmIntegration<'static>>,
}

impl LlvmCodeGenerator {
    pub fn new() -> Result<Self, Error> {
        Ok(Self {
            debug_generator: LlvmDebugCodeGenerator::new(DebugConfig::default()),
            module_name: None,
            web_vibez_integration: None,
        })
    }
    
    pub fn new_with_debug(debug_config: DebugConfig) -> Result<Self, Error> {
        Ok(Self {
            debug_generator: LlvmDebugCodeGenerator::new(debug_config),
            module_name: None,
            web_vibez_integration: None,
        })
    }
    
    pub fn generate_ir(&self, _source: &str) -> Result<String, Error> {
        // Enhanced implementation with debug support
        let mut ir = String::new();
        
        // Module header
        ir.push_str("; Generated by CURSED Compiler with Debug Support\n");
        ir.push_str("target datalayout = \"e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128\"\n");
        ir.push_str("target triple = \"x86_64-pc-linux-gnu\"\n\n");
        
        // Simple main function
        ir.push_str("define i32 @main() {\n");
        ir.push_str("  ret i32 0\n");
        ir.push_str("}\n");
        
        // Add debug utilities if debug is enabled
        if self.debug_generator.debug_enabled() {
            ir.push_str("\n");
            ir.push_str(&self.debug_generator.generate_debug_utilities());
        }
        
        Ok(ir)
    }
    
    /// Generate IR with full debug information
    pub fn generate_ir_with_debug(&mut self, source_file: PathBuf, _source: &str) -> Result<String, Error> {
        // Initialize debug info
        self.debug_generator.initialize_debug_info(source_file.clone(), "CURSED Compiler v1.0".to_string())?;
        
        // Generate a sample module with debug info
        let main_location = SourceLocation::new(source_file.clone(), 1, 1);
        let functions = vec![("main".to_string(), main_location)];
        
        let module_name = source_file.file_stem()
            .and_then(|s| s.to_str())
            .unwrap_or("cursed_module")
            .to_string();
        
        self.module_name = Some(module_name.clone());
        
        self.debug_generator.generate_module_with_debug(module_name, functions)
    }
    
    /// Set debug configuration
    pub fn set_debug_config(&mut self, config: DebugConfig) {
        self.debug_generator.update_debug_config(config);
    }
    
    /// Get debug configuration
    pub fn debug_config(&self) -> &DebugConfig {
        self.debug_generator.debug_config()
    }
    
    /// Check if debug information is enabled
    pub fn debug_enabled(&self) -> bool {
        self.debug_generator.debug_enabled()
    }
    
    /// Get debug statistics
    pub fn debug_statistics(&self) -> String {
        self.debug_generator.debug_statistics()
    }
    
    /// Validate debug information
    pub fn validate_debug(&self) -> Result<(), Vec<String>> {
        self.debug_generator.validate_debug_info()
    }
    
    /// Clear debug information
    pub fn clear_debug(&mut self) {
        self.debug_generator.clear_debug_info();
        self.module_name = None;
    }
    
    /// Get line table for debugging
    pub fn line_table(&self) -> Vec<(u32, String)> {
        self.debug_generator.generate_line_table()
    }
    
    /// Set current source location
    pub fn set_location(&mut self, location: SourceLocation) {
        self.debug_generator.set_current_location(location);
    }
}

impl Default for LlvmCodeGenerator {
    fn default() -> Self {
        Self::new().unwrap()
    }
}
