//! Debug utilities for the CURSED lexer
//!
//! This module provides tools for displaying and debugging the token stream
//! generated by the lexer.

use crate::error::Error;
use crate::lexer::Lexer;

/// Prints a formatted display of all tokens in the input source code
///
/// This function is primarily used for debugging and understanding
/// how the lexer tokenizes source code. It prints each token with its
/// type, literal value, and source location.
///
/// # Arguments
///
/// * `input` - The source code string to tokenize and debug
///
/// # Returns
///
/// Result<(), Error> - Ok if successful, Error if lexical analysis fails
pub fn debug_tokens(input: &str) -> Result<(), Error> {
    let mut lexer = Lexer::new(input);

    println!("TOKEN\t\tLITERAL\t\tLINE:COL");
    println!("-----\t\t-------\t\t-------");

    loop {
        let token = lexer.next_token()?;
        println!(
            "{:?}\t\t{}\t\t{}:{}",
            token,
            token.token_literal(),
            lexer.line,
            lexer.column
        );

        // Stop at EOF
        if token == crate::lexer::Token::Eof {
            break;
        }
    }

    Ok(())
}
