/// Lock File Management System for CURSED
/// 
/// This module provides functionality for managing package lock files
/// including generation, validation, and synchronization.

use std::collections::HashMap;
use std::path::{Path, PathBuf};
use serde::{Deserialize, Serialize};
use crate::package_manager::VersionSpec;

/// Represents a locked package in the lock file
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LockedPackage {
    pub name: String,
    pub version: String,
    pub source: String,
    pub checksum: Option<String>,
    pub dependencies: Vec<String>,
}

/// Main lock file manager
#[derive(Debug)]
pub struct LockFileManager {
    path: PathBuf,
    packages: HashMap<String, LockedPackage>,
    workspace_members: Vec<String>,
}

impl LockFileManager {
    /// Create a new lock file manager
    pub fn new(path: &Path) -> Self {
        Self {
            path: path.to_path_buf(),
            packages: HashMap::new(),
            workspace_members: Vec::new(),
        }
    }
    
    /// Load lock file from disk
    pub fn load(&mut self) -> crate::error::Result<()> {
        if !self.path.exists() {
            return Ok(()); // No lock file exists yet
        }
        
        let content = std::fs::read_to_string(&self.path)?;
        self.parse_lock_file(&content)?;
        
        Ok(())
    }
    
    /// Parse lock file content
    fn parse_lock_file(&mut self, content: &str) -> crate::error::Result<()> {
        // Simple TOML-like parsing for lock file format
        let mut current_section = String::new();
        
        for line in content.lines() {
            let line = line.trim();
            
            if line.is_empty() || line.starts_with('#') {
                continue;
            }
            
            if line.starts_with('[') && line.ends_with(']') {
                // New section
                current_section = line[1..line.len()-1].to_string();
                continue;
            }
            
            if line.contains('=') {
                let parts: Vec<&str> = line.splitn(2, '=').collect();
                if parts.len() == 2 {
                    let key = parts[0].trim();
                    let value = parts[1].trim().trim_matches('"');
                    
                    if current_section == "workspace" {
                        // Workspace member
                        self.workspace_members.push(key.to_string());
                    } else if current_section == "packages" {
                        // Package dependency - create locked package entry
                        let locked_package = LockedPackage {
                            name: key.to_string(),
                            version: value.to_string(),
                            source: "registry".to_string(),
                            checksum: None,
                            dependencies: Vec::new(),
                        };
                        self.packages.insert(key.to_string(), locked_package);
                    }
                }
            }
        }
        
        Ok(())
    }
    
    /// Save lock file to disk
    pub fn save(&self) -> crate::error::Result<()> {
        let content = self.generate_lock_file_content();
        std::fs::write(&self.path, content)?;
        Ok(())
    }
    
    /// Generate lock file content
    fn generate_lock_file_content(&self) -> String {
        let mut content = String::new();
        
        content.push_str("# CURSED Package Lock File\n");
        content.push_str("# This file is automatically generated\n\n");
        
        // Add workspace members if any
        if !self.workspace_members.is_empty() {
            content.push_str("[workspace]\n");
            for member in &self.workspace_members {
                content.push_str(&format!("  {} = \"1.0.0\"\n", member));
            }
            content.push_str("\n");
        }
        
        // Add packages
        if !self.packages.is_empty() {
            content.push_str("[packages]\n");
            for (name, package) in &self.packages {
                content.push_str(&format!("  {} = \"{}\"\n", name, package.version));
            }
        }
        
        content
    }
    
    /// Check if lock file exists
    pub fn exists(&self) -> bool {
        self.path.exists()
    }
    
    /// Get all locked packages
    pub fn get_packages(&self) -> Option<Vec<&LockedPackage>> {
        if self.packages.is_empty() {
            None
        } else {
            Some(self.packages.values().collect())
        }
    }
    
    /// Get workspace members
    pub fn get_workspace_members(&self) -> &[String] {
        &self.workspace_members
    }
    
    /// Add a package to the lock file
    pub fn add_package(&mut self, package: LockedPackage) {
        self.packages.insert(package.name.clone(), package);
    }
    
    /// Remove a package from the lock file
    pub fn remove_package(&mut self, name: &str) -> Option<LockedPackage> {
        self.packages.remove(name)
    }
    
    /// Check if a package is locked
    pub fn is_package_locked(&self, name: &str) -> bool {
        self.packages.contains_key(name)
    }
    
    /// Get locked package information
    pub fn get_package(&self, name: &str) -> Option<&LockedPackage> {
        self.packages.get(name)
    }
    
    /// Set workspace members
    pub fn set_workspace_members(&mut self, members: Vec<String>) {
        self.workspace_members = members;
    }
    
    /// Validate lock file integrity
    pub fn validate(&self) -> crate::error::Result<bool> {
        // Check file exists
        if !self.exists() {
            return Ok(false);
        }
        
        // Check all packages have required fields
        for (name, package) in &self.packages {
            if package.name != *name {
                return Err(crate::error::CursedError::General(
                    format!("Package name mismatch: {} vs {}", name, package.name)
                ));
            }
            
            if package.version.is_empty() {
                return Err(crate::error::CursedError::General(
                    format!("Package {} has empty version", name)
                ));
            }
        }
        
        Ok(true)
    }
    
    /// Get lock file path
    pub fn path(&self) -> &Path {
        &self.path
    }
    
    /// Get lock file statistics
    pub fn stats(&self) -> LockFileStats {
        LockFileStats {
            total_packages: self.packages.len(),
            workspace_members: self.workspace_members.len(),
            file_size: self.path.metadata().map(|m| m.len()).unwrap_or(0),
            exists: self.exists(),
        }
    }
}

/// Statistics about the lock file
#[derive(Debug, Clone)]
pub struct LockFileStats {
    pub total_packages: usize,
    pub workspace_members: usize,
    pub file_size: u64,
    pub exists: bool,
}

/// Lock file validation result
#[derive(Debug, Clone)]
pub struct LockFileValidation {
    pub is_valid: bool,
    pub issues: Vec<String>,
    pub suggestions: Vec<String>,
}

impl LockFileValidation {
    /// Create a new validation result
    pub fn new() -> Self {
        Self {
            is_valid: true,
            issues: Vec::new(),
            suggestions: Vec::new(),
        }
    }
    
    /// Add an issue to the validation result
    pub fn add_issue(&mut self, issue: String) {
        self.is_valid = false;
        self.issues.push(issue);
    }
    
    /// Add a suggestion to the validation result
    pub fn add_suggestion(&mut self, suggestion: String) {
        self.suggestions.push(suggestion);
    }
}

impl Default for LockFileManager {
    fn default() -> Self {
        Self::new(&PathBuf::from("CursedPackage.lock"))
    }
}
